globals:
  React: true
  ReactDOM: true
  PropTypes: true

env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

rules:
  'react/jsx-no-undef': 0

settings:
  react:
    version: '16'
